### ISSUE TITLE
Document browser support and supported JS features

### ISSUE THREAD

**Issue by kaisermann** [vtex/typescript#14]
There's a lot of abstractions in place while developing apps in the IO platform. Without having to mess with bundler, transpiler and/or processor configurations, it's easy to forget that one must be careful about not using some syntax or feature of the language that is not supported throughout our environment.

Things to discover/discuss:

- **What is our official browser support?** Is it different for _storefront_ and _admin_ areas? This is _extremely_ important, not only for JS but also for CSS. i.e I've seen people using `display: grid` and, without an official documentation about browser support, it's possible that we're serving a capped experience for a small portion of our client's users.
- **What kind of polyfills are automatically added to our sites, if any?** i.e Can we use `IntersectionObserver` without thinking about polyfilling it? 
- If a developer wants to use a relative new feature, how she/he is supposed to polyfill it? Should it be encouraged?
- How do we get our (VTEX's) browser usage stats?

There are probably more points related to this, but I couldn't think of all of them right now.

**Comment by luciannojunior** [comment]
Reference: https://github.com/vtex/render-server/blob/master/node/utils/assetLoader.ts#L27

**Comment by klzns** [comment]
For storefront apps IE11 is the oldest browser we do support.

For admin apps maybe we can expect only ever green browsers.

**Comment by kaisermann** [comment]
When documenting this, we can also link to some useful resources such as `Can I Use` and `MDN` and teach people how to check if what they want to use is available in their targeted environment.

**Comment by guilhermebruzzi** [comment]
On globo.com we had browsers class C, browsers class B and browsers class A. And we definitions for each class like: A is full support and pixel perfect per say, B is only visual but allow degradation of some features or light bugs and C is only functional for the main parts.
@kaisermann I think is hard to say what is the (VTEX's) browser usage stats, because it is different for each customer, but we should have a general definition for ecommerce and for admin separated based on use of many different customers (that we can get with Dellacqua from Google Analytics of the customers)

**Comment by kaisermann** [comment]
@guilhermebruzzi Hmmmm, I like those class definitions. We can definitely improve the https://github.com/vtex/javascript/blob/master/docs/Browser%20Support.md with something akin to this at some point.

**Comment by kaisermann** [comment]
Partially done in the above link.
